name: rebuild AIDE
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get apktool
        run: |
          wget -q https://github.com/iBotPeaches/Apktool/releases/download/v2.7.0/apktool_2.7.0.jar
          find
      - name: Get APK
        run: |
          wget -q -O app.apk https://gitee.com/dev-bz/uploading/releases/download/0.0.0/AIDE_3.2.200127.apk
          # https://hole.apkdone.download/s/22FeFJFWr2JQYH8/download
          find -type f
      - name: Decompress resources
        run: java -jar apktool_2.7.0.jar d -s app.apk
      - name: Edit sources
        run: sed s/textVisiblePassword/text/g app/res/values/styles.xml -i
      - name: Build APK
        run: java -jar apktool_2.7.0.jar b app
      - name: Display result
        run: find -type f -name "*.apk"
      - uses: actions/upload-artifact@v3
        with:
          name: output.sdk
          path: app/dist/app.apk
